### ISSUE TITLE
Cannot align sequences if there is a gap character in input fasta

### ISSUE THREAD

**Issue by blake-riley** [refresh-bio/QuickProbs#3]
Looking through the source, `.` seems to be permitted as a gap character.
However, if a sequence in the input fasta contains an internal gap (as below), then QuickProbs segfaults.

This is true regardless of the number of threads selected.

As a minimum working example, if I have:

in.fasta =
```
>seq1
SEQALIGN
>seq2
S.LIGN
```

then the following command will fail:
```bash
~/Downloads/quickprobs-2.06-osx -t 1 -v in.fasta
```

with the following message:
```
30 refinements with OpenMP using 1 threads...
Initialisation...
Column set:
(4,2), (0,1), (1,1), (2,1), (5,1), (9,1),
Iteration started...
1(9), 6(9), 2(9), 5(8), 1(8), Segmentation fault: 11
```

--
OS: macOS 10.12.6
ver: release quickprobs-2.06-osx

**Comment by agudys** [comment]
Hi, As explained in #2, QuickProbs cannot realign sequences with gaps. The segfault you encountered is basically a bug in the verification of an input file.

**Comment by blake-riley** [comment]
I'm closing this discussion in favour of #2 .
